[workspace]
members = ["dev-vault", "dv", "dve"]
resolver = "2"

[workspace.dependencies]
tokio = { version = "1.43.0", features = [
  "fs",
  "io-std",
  "sync",
  "rt-multi-thread",
  "macros",
] }
tracing = { version = "0.1.41" }
async-trait = "0.1.86"
snafu = "0.8.5"
