[package]
name = "dv-api"
version = "0.1.0"
edition = "2021"

[dependencies]
snafu.workspace = true
tokio.workspace = true
tracing.workspace = true
async-trait.workspace = true

bitflags = "2.8.0"
tokio-util = "0.7.13"
tempfile = "3.16.0"
etc-os-release = "0.1.1"
fastrand = "2.3.0"
home = { version = "0.5.11", optional = true }
russh = { version = "0.50.2", features = ["async-trait"] }
russh-config = "0.50.0"
russh-sftp = "2.0.8"
rustix = { version = "0.38.44", features = ["pty"] }
rustix-openpty = "0.1.1"
walkdir = "2.5.0"
zbus = "5.5.0"
camino = "1.1.9"
strum = { version = "0.27.1", features = ["derive"] }


[features]
default = []
path-home = ["dep:home"]
full = ["path-home"]
