[package]
name = "e4pty"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
description = "abstract api for pty"
license = "MIT"

[dependencies]
async-trait.workspace = true
tokio.workspace = true
tracing.workspace = true
tempfile = "3.18.0"

[target.'cfg(not(windows))'.dependencies]
rustix-openpty = "0.2.0"
